### ISSUE TITLE
OSS Slider/Header Updates

### ISSUE THREAD

**Issue by adams9777** [OpenSecuritySummit/oss-website#108]

**Comment by DinisCruz** [comment]
Hi @adams9777  can you add more details on what you mean by "OSS Slider/Header Updates" :)

**Comment by adams9777** [comment]
1. I would like t

![Image](https://user-images.githubusercontent.com/61481273/228963857-2ec3c988-6b01-48f3-ab6e-606cd578fbd0.png)

**Comment by adams9777** [comment]
2. Recommend having a Sign-up as Speaker and Register for the sessions as a call to action after the header texts. Like the example below:


![Image](https://user-images.githubusercontent.com/61481273/228965397-6e656693-3671-4ee5-9d6f-bb619a5f55c8.png)

**Comment by adams9777** [comment]
3. Reduce the header text font size and add a rider below it for more context on what OSS is about: Something in the line of: "Upgrade your cybersecurity knowledge, connect with experts in the field and stay ahead of emerging threats."



![Image](https://user-images.githubusercontent.com/61481273/228966901-7a287c4b-d1b7-4f89-9dbc-d9e4ab022e4d.png)
